### ISSUE TITLE
Compatibility with Home Assistant Community Store

### ISSUE THREAD

**Issue by mjoshd** [kalkih/simple-weather-card#10]
The [Home Assistant Community Store](https://custom-components.github.io/hacs/)  is really awesome and helps greatly in managing custom cards/components/etc. but this custom card is incompatible ☹️ 

```
2019-06-23 13:48:14 [custom_components.hacs.hacs] kalkih/simple-weather-card - No acceptable js files found
2019-06-23 13:48:14 [custom_components.hacs.hacs] kalkih/simple-weather-card - Could not register.
```

Please make it compatible: https://custom-components.github.io/hacs/developer/plugin/

**Comment by royto** [comment]
I made a pr on hacs to support it but was rejected. It is due to bundle name. [This PR](https://github.com/kalkih/simple-weather-card/pull/9) should fix it

**Comment by kalkih** [comment]
Merged https://github.com/kalkih/simple-weather-card/pull/9, HACS will be supported in the next release, will also submit a PR after next release to have the card available by default in HACS.

**Comment by kalkih** [comment]
Should now be available in HACS https://github.com/custom-components/hacs/pull/219 🎉

**Comment by mjoshd** [comment]
Installed via HACS and it's working great! Thanks 😀

**Comment by timdonovanuk** [comment]
Installed via HACs and it's not working great :(

``No card type found``

I have added it to my raw config:

 `` - type: module``
  ``  url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js``

and ensured the file exists at /community_plugin/simple-weather-card/simple-weather-card-bundle.js

**Comment by timdonovanuk** [comment]
Ah..the example is just badly formatted. Doh!

```
type: custom:simple-weather-card
entity: weather.dark_sky
name: in current location
```

rather than:

```
- type: custom:simple-weather-card
  entity: weather.dark_sky
  name: in current location
```
Thanks, lovely plugin :)

**Comment by kalkih** [comment]
You identified the issue, great!
Yes, the examples are formatted for raw config editor / lovelace in yaml mode, as the GUI editor will automatically add the initial dash in the card config.

**Comment by timdonovanuk** [comment]
Ah, is that what that is! I've now noticed a lot of peoples examples had that dash. Got your weather in my dashboard now and it's looking fabulous, thanks again :)
