### ISSUE TITLE
anyway to change the weather icon (condition)

### ISSUE THREAD

**Issue by rgogada** [kalkih/simple-weather-card#12]
I am from Australia and using BOM weather. Unfortunately the conditions they use are not complaint with HA conditions. eg: "Rain" instead of "rainy".

I have created an other template sensor to manipulate this condition to make it complaint with HA conditions but how can I override it on this card. I tried to set the custom state but it does not change the icon (does change the text though). anyway to change the icon? cheers.

**Comment by kalkih** [comment]
Not possible, could possibly add the ability to override the icon-state in the future, but imo the BOM component should be tweaked so that it follows the standard [HA weather states](https://www.home-assistant.io/components/weather/)

**Comment by kflinderman** [comment]
Is it possible to just get the icon to follow whatever the state value is? I'm trying to create a forecast card, and I'm using a custom sensor with tomorrow's weather condition, but it looks like the icon follows what the original condition is.

**Comment by kalkih** [comment]
You can now override the variable the icon-state is based on with a custom sensor.
```yaml
# example
- type: custom:simple-weather-card
  entity: weather.smhi_home
  custom:
    - icon-state: sensor.custom_state_sensor
```

Here are all the available icon states:
* "clear-night"
* cloudy
* overcast
* fog
* hail
* lightning
* "lightning-rainy"
* partlycloudy
* pouring
* rainy
* snowy
* "snowy-rainy"
* sunny
* windy
* "windy-variant"
* humidity

> Is it possible to just get the icon to follow whatever the state value is? I'm trying to create a forecast card, and I'm using a custom sensor with tomorrow's weather condition, but it looks like the icon follows what the original condition is.

Yes, this is now possible if you follow the example above.
