### ISSUE TITLE
Custom element doesn't exist: simple-weather-card in Opera

### ISSUE THREAD

**Issue by Yllelder** [kalkih/simple-weather-card#19]
In Chrome it works correctly, but in Opera the card is not shown.

![error](https://i.imgur.com/LAdf4xA.png)

I have installed the plug-in from HACS and is updated to the latest version.

**Comment by kalkih** [comment]
Okay, just downloaded Opera to try and seems to work fine here, what version of Opera are you running? and Mobile/Desktop?
Aldo, please try clearing cache.

**Comment by Yllelder** [comment]
Well, I'm using Opera for desktop in Windows 10 64 bits, version 62.0.3331.116.

I just checked that with Firefox 68.0.2 (64-bit) I get the same error.

I tried two different computers, one of them didn't have Opera and I did a new installation, and I get the same error.

**Comment by kalkih** [comment]
Hmmm...strange.
Could you try reinstalling the card though HACS, if that doesn't help, would you mind opening developer tools in Opera where you have the issue and look for potential errors in the log?

**Comment by Yllelder** [comment]
Opera shows this in the console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)

Uncaught (in promise) https://xxxxxx.duckdns.org:8123/community_plugin/simple-weather-card/simple-weather-card.js
```

That doesn't find the file `simple-weather-card.js`

**Comment by kalkih** [comment]
Okay, then it's not an issue with the card.
You could try navigating to https://xxxxxx.duckdns.org:8123/community_plugin/simple-weather-card/simple-weather-card.js manually tosee if the file is there, if not, you should double check HACS and reinstall the card.

**Comment by chris-alexander** [comment]
I have the same issue and have been using Chrome. Looks like the js file was renamed to `simple-weather-card-bundle.js` (previously named `simple-weather-card.js`. Changing the url in my lovelace config to `/community_plugin/simple-weather-card/simple-weather-card-bundle.js` fixed it for me.

**Comment by kalkih** [comment]
Ah, true, the bundle was indeed renamed in release [v.0.4.0](https://github.com/kalkih/simple-weather-card/releases/tag/v0.4.0) but that was also the first version with HACS support so if you've installed it through HACS you shouldn't be affected by it, unless HACS has changed how files are saved/named in later versions.
