### ISSUE TITLE
Support for "entity" in tap_action

### ISSUE THREAD

**Issue by Duncank** [kalkih/simple-weather-card#22]
It would be helpful if I could specify a different entity for the `more-info` `tap_action`. I want to open the information for a different entity than the weather-provider.

Button card supports this [in the same way](https://github.com/custom-cards/button-card#action).

In my case, I would like to open the Buienradar-Camera integration when I click on the weather card.
This probably needs to be changed in `src/handleClick.js` on line `6`, by checking if `actionConfig.entity` is specified before using `config.entity`.

**Comment by kalkih** [comment]
Sure!

**Comment by kalkih** [comment]
Should now be possible with the latest version, simply specify `entity: ...` in the `tap_action` object.

Thanks!

**Comment by Duncank** [comment]
Awesome, I've updated and it is working great. Thanks!
