### ISSUE TITLE
Extrema weather attribute shows low temp value as both high and low texts

### ISSUE THREAD

**Issue by xmattjus** [kalkih/simple-weather-card#23]
Hi,
I'm having the following problem with 0.7.1, downloaded from HACS:
![Annotazione 2020-01-23 121942](https://user-images.githubusercontent.com/33389224/72980342-b3630f80-3dda-11ea-9b78-edafe78dcc1a.png)

Extrema weather attribute shows only the low temp value as both the high and low temp texts.

Here follows the yaml config:
![Annotazione 2020-01-23 122440](https://user-images.githubusercontent.com/33389224/72980696-59af1500-3ddb-11ea-9b6c-3c22b30d113d.png)

`sensor.dark_sky_daytime_high_temperature_0d` and `sensor.dark_sky_overnight_low_temperature_0d` have different values in the states console, they're not the same.

I appreciate any help on this, thanks!
xmattjus

**Comment by kalkih** [comment]
Hello,
This has been fixed in the latest release [v0.7.2](https://github.com/kalkih/simple-weather-card/releases/tag/v0.7.2).
Thanks!
