### ISSUE TITLE
Issue with translations

### ISSUE THREAD

**Issue by darkknightjs24** [kalkih/simple-weather-card#30]
I updated to 0.109 and in this card the states are not showing up properly formatted. I think this is because of a new update in the way translations are dealt with in 0.109. 

I have attached an image to this post. As you can see, instead of showing up as "Partly cloudy", it shows "partlycloudy". 

<img width="384" alt="Screen Shot 2020-04-29 at 1 53 02 PM" src="https://user-images.githubusercontent.com/60027350/80646130-08896f80-8a21-11ea-91bb-4259c54a5120.png">

**Comment by ronaldheft** [comment]
Also seeing this issue since 0.109.

**Comment by jackwilsdon** [comment]
We should be using the translations from `component.weather.state._`, as these provide a mapping from state to name (i.e. `component.weather.state._.partlycloudy` -> `Partly Cloudy`).
