### ISSUE TITLE
Do not display low temp if not available

### ISSUE THREAD

**Issue by royto** [kalkih/simple-weather-card#4]
I'm using [OpenWeatherMap](https://www.home-assistant.io/components/weather.openweathermap/) component and it does not support low temperature.

As the result, the card is displaying empty value for low temp ... 

![image](https://user-images.githubusercontent.com/6990995/53841439-12d6e780-3f9d-11e9-9646-624f87200bdf.png)

It could be better to display low temp only if available

**Comment by kalkih** [comment]
Fixed in latest release.
