### ISSUE TITLE
Wrong Extrema calculation

### ISSUE THREAD

**Issue by smmoroz** [kalkih/simple-weather-card#40]
Hi!

Extrema (high and low temperatures) is computed using just forecast[0]. But in many cases forecast[0] is just night, while forecast[1] is day. In this case high = forecast[1].temperature and low =forecast[0].templow.

I would suggest a more general way:

high = max of forecast[i].temperature 
low = low of forecast[i].templow

Thanks for your great work!

**Comment by gonzotek** [comment]
Agree with smmoroz on the suggested general approach.

I would also like to note that at least with the Dark Sky weather platform (which is admittedly due for deprecation eventually), forecast can be the next X _hours_ (not days), **and** there is no templow shown in the entity attributes.  Perhaps the algorithm could be further improved by checking for a templow, and if non-existant, _optionally_ using the min of forecast[i].temperature instead?
