### ISSUE TITLE
Weather card is not working with 0.116.0b0

### ISSUE THREAD

**Issue by TheZoker** [kalkih/simple-weather-card#43]
This is what the card looks like on version 0.115.x:
![Screenshot_2020 09 30_23h41m19s_030_](https://user-images.githubusercontent.com/1368405/94742946-d33dd080-0376-11eb-95f7-958b28c1cffc.png)

And here is what the card looks like on version 0.116.0b0 (just gone):
![Screenshot_2020 09 30_23h42m27s_031_](https://user-images.githubusercontent.com/1368405/94742975-e486dd00-0376-11eb-86a2-af2552c23e62.png)

The HTML element is just empty:
![Screenshot_2020 09 30_23h45m30s_032_](https://user-images.githubusercontent.com/1368405/94743080-1304b800-0377-11eb-8178-02e478f57b3b.png)

Let me know, if you need more info about this issue :)

**Comment by kalkih** [comment]
Strange, looks like the custom element isn't defined.
Is this the only custom card that's not working?

**Comment by TheZoker** [comment]
Yes `mini-media-player`, `button-card` and `mini-graph-card` are working fine

**Comment by jimz011** [comment]
Same here, maybe it has something to do with the lazy loading?

**Comment by hmmbob** [comment]
With the 0.116.0 release, this bug is now also present in the current release.

**Comment by kalkih** [comment]
Try the new release of the card, should hopefully work, did the trick on my setup 🤞

**Comment by hmmbob** [comment]
Yes, new version fixed it for me too!

Tx!

**Comment by hmmbob** [comment]
Another issue seems to popup with 0.116: if you click the card, a "generic HA popup" (the 'more info' dialog) shows, but is bound within the size of the card (and thus hardly readable)

**Comment by kalkih** [comment]
I don't see that behaviour myself, what does your setup look like, do you have it wrapped inside other cards perhaps, stacks e.t.c.?

**Comment by hmmbob** [comment]
Yeah, I actually do that indeed.

https://github.com/hmmbob/HomeAssistantConfig/blob/48d5650c6406a3e8edcb49b8384aed5700eea19f/lovelace/1-start.yaml#L57-L96

**Comment by kalkih** [comment]
Is probably nesting it inside either custom:state-switch or vertical-stack that's causing this then, custom:state-switch would be my first guess. I don't think this is anything I can resolve on my end since the more-info dialog isn't really a part of the card.

**Comment by TheZoker** [comment]
Mine looks like this:
```yaml
type: vertical-stack
cards:
  - backdrop: true
    entity: weather.openweathermap
    name: ' '
    type: 'custom:simple-weather-card'
...
```

**Comment by kalkih** [comment]
And you experience the more-info dialog issue as well?

> Another issue seems to popup with 0.116: if you click the card, a "generic HA popup" (the 'more info' dialog) shows, but is bound within the size of the card (and thus hardly readable)

**Comment by hmmbob** [comment]
Issue with the more info dialog is gone for me, by either removing Custom Header (as it was deprecated) or upgrading to 0.116.2 - I unfortunately do not know which one of the two worked 😄

**Comment by TheZoker** [comment]
I'll close this, as the issue seems to be resolved in the latest release! Thanks
