### ISSUE TITLE
is there any way to make it work with weather:BOM?

### ISSUE THREAD

**Issue by rgogada** [kalkih/simple-weather-card#5]
Here in Australia we use BOM
https://www.home-assistant.io/components/weather.bom/

I tried using it but no card is displayed. Anyway to make it work? Thanks.

**Comment by kalkih** [comment]
I'm not sure why it wouldn't, I'll check tomorrow and report back, thanks.

**Comment by kalkih** [comment]
Okay, so I don't live in Australia but I went ahead and set up a bom weather entity, and it seems like the bom sensor just doesn't expose much data.

This is literally all the attribute the bom component seem to expose:
```json
{
  "attribution": "Data provided by the Australian Bureau of Meteorology",
  "pressure": 1024.2,
  "temperature": 14.3,
  "wind_bearing": 157.5,
  "humidity": 52,
  "wind_speed": 6,
  "friendly_name": "BOM Adelaide (Kent Town)"
}
```
Not even a state 😞 

So the only thing that would show up on the card would be the current temp and possibly the humidity/wind_speed.

**Comment by kalkih** [comment]
I'll make the card more robust, so it'll at least show up.

**Comment by rgogada** [comment]
> I'll make the card more robust, so it'll at least show up.

thanks. appreciate it.

**Comment by kalkih** [comment]
Now supported in the latest release.
