### ISSUE TITLE
HA 2021.6 Lit version upgrade

### ISSUE THREAD

**Issue by hmmbob** [kalkih/simple-weather-card#51]
Raising for awareness: this card is importing Lit in a way that might break in HA 2021.6 which ships with Lit 2.0

For more information, see https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/

**Comment by Tamsy** [comment]
Confirmed. simple-weather-card is not working anymore with 2021.6.x

**Comment by hmmbob** [comment]
You sure it isn't another issue? It's working just fine here 🤷🏻 

(Probably the import still needs to be fixed, yet this wasn't breaking it appears)

**Comment by Tamsy** [comment]
> You sure it isn't another issue? It's working just fine here 🤷🏻
> 
> (Probably the import still needs to be fixed, yet this wasn't breaking it appears)

Oups wrong card: My report should have gone to the "animated-weather-card" which is partly broken (animations dom't work anymore).

So sorry for the noise. Please disregard.
