### ISSUE TITLE
Card not showing up: Uncaught TypeError: A is not a function

### ISSUE THREAD

**Issue by lunatik98** [kalkih/simple-weather-card#57]
Error: http://192.168.1.12:8123/hacsfiles/simple-weather-card/simple-weather-card-bundle.js?hacstag=172998062080:1:33169 Uncaught TypeError: A is not a function

I already reinstalled the card, cleared the cache and rebooted...can you please help?

**Comment by pawelma** [comment]
Same here. 
![image](https://user-images.githubusercontent.com/1849200/165278580-09e849d7-a723-42c4-bf50-fcb3ddb8a5c2.png)
Other custom cards works fine. Tried to copy the bundle from releases with no effect.

**Comment by MiBe17** [comment]
Same here!

**Comment by Soben** [comment]
I am currently also experiencing this issue. Fresh install from scratch, following instructions from Lewis over at Everything Smart Home.

**Comment by kalkih** [comment]
I wasn't able to reproduce the issue but made some changes to the code, please try the latest release, hopefully fixes the issue 🤞🏼

**Comment by pawelma** [comment]
It works to me now. Thanks.

**Comment by lunatik98** [comment]
seems to work now, thanks
