### ISSUE TITLE
Need v0.8.2. to be a github release

### ISSUE THREAD

**Issue by galak** [kalkih/simple-weather-card#58]
When trying to install with HACS we only see version 0.8.0 since 0.8.2 is not a github release.  Can you make a github release of 0.8.2 so HACS can install that version.

**Comment by kalkih** [comment]
It should be a github release already (or at least it has been before).
I've noticed recently that Github seem to hide patch releases, a quick edit and save of the release seems to do the trick so I did just that now.

Let me know if it helped.

https://github.com/kalkih/simple-weather-card/releases/tag/v0.8.2

**Comment by galak** [comment]
Thanks that seems to have done the trick.
