### ISSUE TITLE
Does not install correctly via HACS

### ISSUE THREAD

**Issue by JSaterdalen** [kalkih/simple-weather-card#59]
Installing simple-weather-card through HACS does not seem to install and unpack correctly.

HACS is unable to find any releases, and after installation, there is no `simple-weather-card-bundle.js` to be found.

**Missing Releases**
<img width="364" alt="image" src="https://user-images.githubusercontent.com/6761188/167731304-10680e6f-d055-4c4e-8ed1-9a0e29158d64.png">

_That commit ID should normally be a version number—clicking it brings up the releases page in the repo (which is empty)._

**Missing correct JS file**
<img width="199" alt="image" src="https://user-images.githubusercontent.com/6761188/167731280-0f3770b4-2546-4e95-8ec3-00dd91636d57.png">

This manifests in the resource being null:
`/hacsfiles/simple-weather-card/null?hacstag=172998062`

**Comment by kalkih** [comment]
Strange, I do not have HACS installed, will take a look at a later date.
The card definitely has releases, see the [release](https://github.com/kalkih/simple-weather-card/releases) page.

https://github.com/kalkih/simple-weather-card/commit/e9e34a8239f88b53cf0b2cfa745df5a0f529eb09 was the commit id of the latest release (prior to the one I made an hour ago.) and seems to be correct.

**Comment by JSaterdalen** [comment]
Strange. Since the new release it is displaying correctly.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/6761188/167938843-2564ff02-4bc4-4852-a4a8-4df4cc6f94cb.png">

Previously, clicking the commit ID loaded the same release page but it was blank.

**Comment by kalkih** [comment]
Strange, I have no explanation 🤷🏼‍♂️  but great that it works now!
