### ISSUE TITLE
Add own weather sensor

### ISSUE THREAD

**Issue by lubbertkramer** [kalkih/simple-weather-card#6]
Hi,

i'm using [Weatherflow ](http://weatherflow.com/smart-home-weather-stations/) as my weather station and therefor have several seperated sensors. I love the work you do on the other cards and i hoped this card could become more configurable? 

Will it be possible to use your own sensors for the weather and they will be mapped on the card?

Otherwise will it be possible to have a blank card and just use it like picture elements and map our own sensors on it?

See below a screenshot of my sensors
![image](https://user-images.githubusercontent.com/8224586/53844492-2a669e00-3fa6-11e9-9111-8f4c0ec30269.png)

Thanks!

**Comment by kalkih** [comment]
Hey.
Maybe in the future, not sure how we would get the weather condition though, what do you think?

> Otherwise will it be possible to have a blank card and just use it like picture elements and map our own sensors on it?

Isn't this exactly what the picture elements card does already?

**Comment by royto** [comment]
Same thing with [netatmo weather station](https://www.home-assistant.io/components/sensor.netatmo/)

**Comment by TinusK** [comment]
Why not just add the possibility to add a current temperature sensor that is then used to display the current temperature and not the current temperature from the weather entity.

I myself have an actual weather station on the roof and would like to use your card with the weather forecast from the weather entity in HA but with the actual temperature sensed on the roof :)

**Comment by kalkih** [comment]
Yeah, If anyone wanna implement this and submit a PR, I would very much appreciate it.

**Comment by lubbertkramer** [comment]
Here i solved it by using https://community.home-assistant.io/t/smartweather-get-local-weather-data-combined-with-dark-sky-forecast/105151 which added a weather component from my own weatherstation Weatherflow. Now it's a weathercomponent it can be used with this card

In the picture below you see the card, the temp before @ Thuis (@ home) is my local temperature from weatherflow

![WhatsApp Image 2019-05-25 at 20 14 38](https://user-images.githubusercontent.com/8224586/58373158-d4145600-7f29-11e9-84ab-4a6d05a066fc.jpeg)

**Comment by kalkih** [comment]
You can now use custom sensors with the new `custom` option!
