### ISSUE TITLE
Is this still working as of current date ? 06-28-2022

### ISSUE THREAD

**Issue by Triskelen** [kalkih/simple-weather-card#62]
installed it with HACS 
and can't find it in my cards 
when i try to add it manually i get a error there is no such card.

kind regards

**Comment by bkr1969** [comment]
I think it is not

**Comment by kalkih** [comment]
I think it should be working, can you post the card configuration when you get this error?

**Comment by bkr1969** [comment]
I think the issue was with the OpenWeatherMap update.  There is no longer a weather.openweathermap entity that works.  Switched to weather.home and it works fine.
