### ISSUE TITLE
custom:simple-weather-card does not exist

### ISSUE THREAD

**Issue by 0546timm** [kalkih/simple-weather-card#65]
Hi,

Im getting this error.. 

- Removed cache
- Removed history
- Tried different browsers
- Tried incognito (on different browsers)
- Tried below, but nothing changed. Getting an error, it seems it doesnt accept the 'js' instead of 'module'..

_If you are getting "Custom element doesn't exist: simple-weather-card", or are running an older browser try replacing type: module with type: js in the resource reference in ui-lovelace.yaml or in the raw config editor._

![image](https://user-images.githubusercontent.com/56634248/210274308-07c10c6c-b78e-4561-ab86-12629c30fd2d.png)

![Schermafbeelding 2023-01-02 210021](https://user-images.githubusercontent.com/56634248/210273965-22993a8d-b459-404b-be3f-8441d9489396.png)

Any ideas?

**Comment by ingeniumdesign** [comment]
i dont found the plugin in the HACS Installer....

**Comment by 0546timm** [comment]
> 

I don't see it too anymore, but you can manually install it like described in the docs.. (if it works eventually... )

**Comment by 0546timm** [comment]
My bad, I'm a retard, put the .JS in the wrong folder on my RPi. Solved by moving it one folder up..
