### ISSUE TITLE
After HA 2023.4 update, Weather attribute issue

### ISSUE THREAD

**Issue by limitless00net** [kalkih/simple-weather-card#67]
After HA 2023.4 update, Weather attribute is displayed in lowercase letters and no spaces.

![20230414_184](https://user-images.githubusercontent.com/64896798/231934718-20e9f8d7-869d-4f44-b790-27c6df520f7f.png)

**Comment by wimb0** [comment]
I am having the same issue since HA 2023.4
![image](https://user-images.githubusercontent.com/11030068/232026652-f337531b-1815-4c38-973b-dc194e486538.png)

**Comment by Smandurlo** [comment]
Same here. There is another problem: it is not translated. I had the weather attribute in Italian, now it is in English. It happened to both my HA installations

**Comment by Fruitsmart** [comment]
The same here. it is not translate to german.

**Comment by edwardtich1** [comment]
how to set it up?

**Comment by niekniek89** [comment]
Here the same issue, nog translation.
is it possible to change this yourself to:

simple-weather-card-bundle.js

or will there be an update?

**Comment by se-bastiaan** [comment]
Yes you can definitely change the key in your local bundled JS file.
https://gist.github.com/se-bastiaan/93b481797c141a3e5868fc57bd2124ef

**Comment by limitless00net** [comment]
@kalkih Please merge this pull requests: https://github.com/kalkih/simple-weather-card/pull/68

**Comment by edwardtich1** [comment]
> Да, вы определенно можете изменить ключ в случайно связанном JS-файле. https://gist.github.com/se-bastiaan/93b481797c141a3e5868fc57bd2124ef

what needs to be changed here?

**Comment by edwardtich1** [comment]
> Это вызывает изменениями в интерфейсе HA: [https://github.com/home-assistant/frontend/pull/15820/files.](https://github.com/home-assistant/frontend/pull/15820/files)
> 
> Здесь необходимо настроить ключ перевода: [https://github.com/kalkih/simple-weather-card/blob/master/src/weather.js#L80 .](https://github.com/kalkih/simple-weather-card/blob/master/src/weather.js#L80)
> 
> Возможно, также нужна обратная совместимость, но я не знаю, как это сделать.

I don't have such a file

**Comment by kalkih** [comment]
https://github.com/kalkih/simple-weather-card/pull/68 now merged, let me know if issue is resolved with the altest version!

**Comment by wimb0** [comment]
Installed the update, v 0.8.4. Doesn't work:
```
Uncaught (in promise) ReferenceError: useComponentEntityTranslations is not defined
    get state simple-weather-card-bundle.js:1
    value simple-weather-card-bundle.js:1
    value simple-weather-card-bundle.js:1
    update lit-element.ts:160
    performUpdate reactive-element.ts:1331
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
```
![image](https://github.com/kalkih/simple-weather-card/assets/11030068/b636cea9-fe77-4c20-8c55-b0d6621c2cc4)

Check versions and modified date, and they are up to date.

**Comment by kalkih** [comment]
Thanks, I see the issue.
I will put up a new version tomorrow, way past 🛌-time now.

**Comment by edwardtich1** [comment]
updated version
it is not translated

**Comment by limitless00net** [comment]
> Thanks, I see the issue. I will put up a new version tomorrow, way past 🛌-time now.

I wonder whether you put up a new version again.

**Comment by kalkih** [comment]
Sorry, new version is up now https://github.com/kalkih/simple-weather-card/releases/tag/v0.8.5
I do no longer run HA myself so unable to test stuff and did unfortunately miss the issue while reviewing the PR.

**Comment by Smandurlo** [comment]
It works :-)
![Uploading Screenshot_2023-05-12-23-01-10-783_io.homeassistant.companion.android-edit.jpg…]()

**Comment by fx-host-assistant** [comment]
It works :-) 
![Screenshot_2023-05-12-23-01-10-783_io homeassistant companion android-edit](https://github.com/kalkih/simple-weather-card/assets/36647269/5476fc37-2d6c-46d1-8c0a-db1f77ef548d)

**Comment by edwardtich1** [comment]
updated version
it is not translated

**Comment by fx-host-assistant** [comment]
Are you sure? Mine is ok
![Screenshot_2023-05-13-10-53-41-274_io homeassistant companion android-edit](https://github.com/kalkih/simple-weather-card/assets/36647269/de457040-d98d-4a20-8f88-864d6f8c5ccd)

**Comment by edwardtich1** [comment]
![Uploading IMG_20230513_115720.jpg…]()

**Comment by edwardtich1** [comment]
it is not translated

**Comment by fx-host-assistant** [comment]
> it is not translated

What is your HA version?

**Comment by edwardtich1** [comment]
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

**Comment by fx-host-assistant** [comment]
I have 2 HA and both are fixed. I use openweather map and istituto Portuguese do mar as weather forecast services, if that makes any difference

**Comment by edwardtich1** [comment]
AccuWeather, Inc.
Forecast Met.no
Not working

**Comment by Mariusthvdb** [comment]
sorry for following up this closed issue, but please could anyone let me know if the wind direction should be translated?

I use Dutch, and can see the condition in Dutch alright, but the direction is still using SW, while in Dutch this should be ZW

<img width="520" alt="Scherm­afbeelding 2024-01-14 om 15 03 41" src="https://github.com/kalkih/simple-weather-card/assets/33354141/a19bb00d-79da-4409-aa0b-3059b4473aee">

**Comment by se-bastiaan** [comment]
@Mariusthvdb It's SW instead of ZW for me too. The shown values are hard-coded though, so they're not going to change based on your UI language.

It should be possible to translate it though:
https://github.com/home-assistant/frontend/blob/7c389a6cf0e925325c90d8948a9fb7dc7f070bb5/src/data/weather.ts#L198C7-L200C8

**Comment by Mariusthvdb** [comment]
sure, thanks, I did have a look at that, would be easy enough.
would be much better though if it supported translations via localize like the modern frontend does
not sure if this card is still maintained.
