### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by SebastianPietschner** [kalkih/simple-weather-card#8]
The different icons for weather types aren't showing up on the card. Do I need to move the icons to a certain directory?

**Comment by kalkih** [comment]
Hi,
The icons are embedded into the release bundle to streamline the install, so no need to download any additional files.

Which weather platform are you using? Could it be that the condition isn't exposed by the platform?

**Comment by jtscott** [comment]
I am having this issue too, using ecobee component for weather

**Comment by kalkih** [comment]
Okay, could you check what state the entity report when you aren't seeing the weather icon. You can check this by navigating to `<your-ha>/dev-state`

HA has some standardized weather condition which most weather components follow, these conditions are then mapped to the individual weather icons.

**Comment by jtscott** [comment]
Apparently ecobee is using darksky as their source? https://www.reddit.com/r/ecobee/comments/a53f0s/weather_source/

Right now the card is blank but my weather component state is 'Clear'

**Comment by kalkih** [comment]
Okay, `Clear` isn't one of the standardized weather conditions in HA, you can find them all here.
https://www.home-assistant.io/components/weather/#condition-mapping

I suppose weather icons doesn't shows up in the default weather card either?

I could add additional mappings of coditions to the card, but I would need to know all possible weather conditions in order to do that.

**Comment by jtscott** [comment]
Ah yeah, no icons on the default weather card either, I will switch over to dark sky. I can report back as I find more ecobee states, but I don't have a source that I am aware of other than waiting and logging.

**Comment by kalkih** [comment]
That would be great!
Yeah, I looked for the conditions in the ecobee weather component but they weren't exposed in there so I guess they are directly from the ecobee api.

**Comment by jtscott** [comment]
Here is what I got from the ecobee component so far:

`{
  "temperature": 13,
  "humidity": 49,
  "pressure": 1026,
  "wind_bearing": 162,
  "wind_speed": 1,
  "visibility": 16000,
  "attribution": "Ecobee weather provided by FI:718778 at 2019-06-09 17:33:45",
  "forecast": [
    {
      "datetime": "2019-06-09T11:33:45",
      "condition": "Partly Cloudy",
      "temperature": 17,
      "templow": 3,
      "pressure": 1026,
      "wind_speed": 16000,
      "humidity": 49
    },
    {
      "datetime": "2019-06-10T00:00:00",
      "condition": "Mostly cloudy throughout the day.",
      "temperature": 17,
      "templow": 6,
      "pressure": 1019,
      "wind_speed": 15000,
      "humidity": 54
    },
    {
      "datetime": "2019-06-11T00:00:00",
      "condition": "Partly cloudy throughout the day.",
      "temperature": 20,
      "templow": 8,
      "pressure": 1022,
      "wind_speed": 16000,
      "humidity": 60
    },
    {
      "datetime": "2019-06-12T00:00:00",
      "condition": "Mostly cloudy starting in the evening.",
      "temperature": 23,
      "templow": 9,
      "pressure": 1017,
      "wind_speed": 16000,
      "humidity": 56
    },
    {
      "datetime": "2019-06-13T00:00:00",
      "condition": "Rain in the evening.",
      "temperature": 25,
      "templow": 12,
      "pressure": 1007,
      "wind_speed": 12000,
      "humidity": 59
    }
  ],
  "friendly_name": "Main Floor"
}`

Just not sure how to find the data from the station 'FI:718778'?

**Comment by Stark003** [comment]
Yes, sorry. I'm using the BOM weather card which probably doesn't support icons.

**Comment by kalkih** [comment]
Hey,
The icon are is now hidden (will not take up space) if the weather state is unknown and there's no icon available.
